// provinces
const provinces =  [
    {
        "id": 3846585024678,
        "country_id": 366676476070,
        "name": "Abra",
        "code": "PH-ABR",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585057446,
        "country_id": 366676476070,
        "name": "Agusan del Norte",
        "code": "PH-AGN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846585090214,
        "country_id": 366676476070,
        "name": "Agusan del Sur",
        "code": "PH-AGS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846585122982,
        "country_id": 366676476070,
        "name": "Aklan",
        "code": "PH-AKL",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846585155750,
        "country_id": 366676476070,
        "name": "Albay",
        "code": "PH-ALB",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585188518,
        "country_id": 366676476070,
        "name": "Antique",
        "code": "PH-ANT",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846585221286,
        "country_id": 366676476070,
        "name": "Apayao",
        "code": "PH-APA",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585254054,
        "country_id": 366676476070,
        "name": "Aurora",
        "code": "PH-AUR",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585286822,
        "country_id": 366676476070,
        "name": "Basilan",
        "code": "PH-BAS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846585319590,
        "country_id": 366676476070,
        "name": "Bataan",
        "code": "PH-BAN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585352358,
        "country_id": 366676476070,
        "name": "Batanes",
        "code": "PH-BTN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585385126,
        "country_id": 366676476070,
        "name": "Batangas",
        "code": "PH-BTG",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585417894,
        "country_id": 366676476070,
        "name": "Benguet",
        "code": "PH-BEN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585450662,
        "country_id": 366676476070,
        "name": "Biliran",
        "code": "PH-BIL",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846585483430,
        "country_id": 366676476070,
        "name": "Bohol",
        "code": "PH-BOH",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846585516198,
        "country_id": 366676476070,
        "name": "Bukidnon",
        "code": "PH-BUK",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846585548966,
        "country_id": 366676476070,
        "name": "Bulacan",
        "code": "PH-BUL",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585581734,
        "country_id": 366676476070,
        "name": "Cagayan",
        "code": "PH-CAG",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585614502,
        "country_id": 366676476070,
        "name": "Camarines Norte",
        "code": "PH-CAN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585647270,
        "country_id": 366676476070,
        "name": "Camarines Sur",
        "code": "PH-CAS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585680038,
        "country_id": 366676476070,
        "name": "Camiguin",
        "code": "PH-CAM",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846585712806,
        "country_id": 366676476070,
        "name": "Capiz",
        "code": "PH-CAP",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846585745574,
        "country_id": 366676476070,
        "name": "Catanduanes",
        "code": "PH-CAT",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585778342,
        "country_id": 366676476070,
        "name": "Cavite",
        "code": "PH-CAV",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846585811110,
        "country_id": 366676476070,
        "name": "Cebu",
        "code": "PH-CEB",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846585843878,
        "country_id": 366676476070,
        "name": "Cotabato",
        "code": "PH-NCO",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846585942182,
        "country_id": 366676476070,
        "name": "Davao de Oro",
        "code": "PH-COM",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846585974950,
        "country_id": 366676476070,
        "name": "Davao del Norte",
        "code": "PH-DAV",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846586007718,
        "country_id": 366676476070,
        "name": "Davao del Sur",
        "code": "PH-DAS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846585876646,
        "country_id": 366676476070,
        "name": "Davao Occidental",
        "code": "PH-DVO",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846585909414,
        "country_id": 366676476070,
        "name": "Davao Oriental",
        "code": "PH-DAO",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846586040486,
        "country_id": 366676476070,
        "name": "Dinagat Islands",
        "code": "PH-DIN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846586073254,
        "country_id": 366676476070,
        "name": "Eastern Samar",
        "code": "PH-EAS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846586106022,
        "country_id": 366676476070,
        "name": "Guimaras",
        "code": "PH-GUI",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846586138790,
        "country_id": 366676476070,
        "name": "Ifugao",
        "code": "PH-IFU",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586171558,
        "country_id": 366676476070,
        "name": "Ilocos Norte",
        "code": "PH-ILN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586204326,
        "country_id": 366676476070,
        "name": "Ilocos Sur",
        "code": "PH-ILS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586237094,
        "country_id": 366676476070,
        "name": "Iloilo",
        "code": "PH-ILI",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846586269862,
        "country_id": 366676476070,
        "name": "Isabela",
        "code": "PH-ISA",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586302630,
        "country_id": 366676476070,
        "name": "Kalinga",
        "code": "PH-KAL",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586335398,
        "country_id": 366676476070,
        "name": "La Union",
        "code": "PH-LUN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586368166,
        "country_id": 366676476070,
        "name": "Laguna",
        "code": "PH-LAG",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586400934,
        "country_id": 366676476070,
        "name": "Lanao del Norte",
        "code": "PH-LAN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846586433702,
        "country_id": 366676476070,
        "name": "Lanao del Sur",
        "code": "PH-LAS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846586466470,
        "country_id": 366676476070,
        "name": "Leyte",
        "code": "PH-LEY",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846586499238,
        "country_id": 366676476070,
        "name": "Maguindanao",
        "code": "PH-MAG",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846586532006,
        "country_id": 366676476070,
        "name": "Marinduque",
        "code": "PH-MAD",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586564774,
        "country_id": 366676476070,
        "name": "Masbate",
        "code": "PH-MAS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586597542,
        "country_id": 366676476070,
        "name": "Metro Manila",
        "code": "PH-00",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "NCR"
    },
    {
        "id": 3846586630310,
        "country_id": 366676476070,
        "name": "Misamis Occidental",
        "code": "PH-MSC",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846586663078,
        "country_id": 366676476070,
        "name": "Misamis Oriental",
        "code": "PH-MSR",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846586695846,
        "country_id": 366676476070,
        "name": "Mountain Province",
        "code": "PH-MOU",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586728614,
        "country_id": 366676476070,
        "name": "Negros Occidental",
        "code": "PH-NEC",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846586761382,
        "country_id": 366676476070,
        "name": "Negros Oriental",
        "code": "PH-NER",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846586794150,
        "country_id": 366676476070,
        "name": "Northern Samar",
        "code": "PH-NSA",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846586826918,
        "country_id": 366676476070,
        "name": "Nueva Ecija",
        "code": "PH-NUE",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586859686,
        "country_id": 366676476070,
        "name": "Nueva Vizcaya",
        "code": "PH-NUV",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586892454,
        "country_id": 366676476070,
        "name": "Occidental Mindoro",
        "code": "PH-MDC",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586925222,
        "country_id": 366676476070,
        "name": "Oriental Mindoro",
        "code": "PH-MDR",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586957990,
        "country_id": 366676476070,
        "name": "Palawan",
        "code": "PH-PLW",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846586990758,
        "country_id": 366676476070,
        "name": "Pampanga",
        "code": "PH-PAM",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587023526,
        "country_id": 366676476070,
        "name": "Pangasinan",
        "code": "PH-PAN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587056294,
        "country_id": 366676476070,
        "name": "Quezon",
        "code": "PH-QUE",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587089062,
        "country_id": 366676476070,
        "name": "Quirino",
        "code": "PH-QUI",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587121830,
        "country_id": 366676476070,
        "name": "Rizal",
        "code": "PH-RIZ",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587154598,
        "country_id": 366676476070,
        "name": "Romblon",
        "code": "PH-ROM",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587187366,
        "country_id": 366676476070,
        "name": "Samar",
        "code": "PH-WSA",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846587220134,
        "country_id": 366676476070,
        "name": "Sarangani",
        "code": "PH-SAR",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587252902,
        "country_id": 366676476070,
        "name": "Siquijor",
        "code": "PH-SIG",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846587285670,
        "country_id": 366676476070,
        "name": "Sorsogon",
        "code": "PH-SOR",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587318438,
        "country_id": 366676476070,
        "name": "South Cotabato",
        "code": "PH-SCO",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587351206,
        "country_id": 366676476070,
        "name": "Southern Leyte",
        "code": "PH-SLE",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Visayas"
    },
    {
        "id": 3846587383974,
        "country_id": 366676476070,
        "name": "Sultan Kudarat",
        "code": "PH-SUK",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587416742,
        "country_id": 366676476070,
        "name": "Sulu",
        "code": "PH-SLU",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587449510,
        "country_id": 366676476070,
        "name": "Surigao del Norte",
        "code": "PH-SUN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587482278,
        "country_id": 366676476070,
        "name": "Surigao del Sur",
        "code": "PH-SUR",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587515046,
        "country_id": 366676476070,
        "name": "Tarlac",
        "code": "PH-TAR",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587547814,
        "country_id": 366676476070,
        "name": "Tawi-Tawi",
        "code": "PH-TAW",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587580582,
        "country_id": 366676476070,
        "name": "Zambales",
        "code": "PH-ZMB",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Luzon"
    },
    {
        "id": 3846587646118,
        "country_id": 366676476070,
        "name": "Zamboanga del Norte",
        "code": "PH-ZAN",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587678886,
        "country_id": 366676476070,
        "name": "Zamboanga del Sur",
        "code": "PH-ZAS",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    },
    {
        "id": 3846587613350,
        "country_id": 366676476070,
        "name": "Zamboanga Sibugay",
        "code": "PH-ZSI",
        "tax": 0,
        "tax_name": "VAT",
        "tax_type": null,
        "shipping_zone_id": null,
        "tax_percentage": 0,
        "island": "Mindanao"
    }
];

module.exports = {
    provinces
}